# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d39bf19d6f4ba393d45f2eb392b9e11079ef46ff1a27557bb65937d899a61240f31b1ae6c66e780c4d125be06bef1391235b657a2b720805c3cb86c681f454

test:
  secret_key_base: 6751617d7119b60da879322bfd2550f6f4a08abf2a4b5793dc373dae97b9a382307f3486441176db07eb71464ab643d1a9d6e64847d58abde0fa327c9e394944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
